### ISSUE TITLE
Document the query noquotes: true parameter

### ISSUE THREAD

**Issue by chrishakai** [bhovhannes/svg-url-loader#10]
It took me a while to figure this out (I'm new to webpack), I was about to fork your repository and edit things so that I could remove the quotes. If you have the following in your documentation stating that you can remove quotes by adding the query parameter to the webpack.config.js it would be much easier to use.

```
module.exports = {
  //...
    module: {
        loaders: [
            { test: /\.svg/, loader: 'svg-url-loader', query: { noquotes: true }}
        ]
    },
    //...
};
```

**Comment by bhovhannes** [comment]
Hi @chrishakai , I've included more details in the docs.
Sending you the link to webpack documentation regarding using loaders: http://webpack.github.io/docs/using-loaders.html
If you're new to webpack, it will be useful. The link above is mentioned in almost all webpack loaders, and so did I in svg-url-loader.
