### ISSUE TITLE
Make loader to always behave as `stripdeclarations=true`

### ISSUE THREAD

**Issue by bhovhannes** [bhovhannes/svg-url-loader#104]
We need to test if SVG without XML declaration works ok in all modern browsers, including IE11 and Edge.
And if this is the case, `stripdeclarations` option can be removed and set to true to make it a default behaviour of the loader.

cc @malthejorgensen

**Comment by iamakulov** [comment]
Just tested this.

Here’s the Codepen I used for testing. It includes two sets of `img` and `div` with `background-image` – one with a XML declaration, and another without it: https://codepen.io/iamakulov/pen/KybaEQ

Both sets of images work OK in latest Edge, Chrome, Firefox and IE. To keep options simple, I’d probably deprecate this option and remove it with the next major version. What do you think?

**Microsoft EdgeHTML 16.16299**
![image](https://user-images.githubusercontent.com/2953267/33464179-17a9c9cc-d652-11e7-8b4e-0188e143b835.png)

**Google Chrome 64.0.3281.0 (Official Build) canary (64-bit)**
![image](https://user-images.githubusercontent.com/2953267/33464285-8da85d0a-d652-11e7-90ac-3d3ef35e3b03.png)

**Firefox 58.0b7 (64-bit)**
![image](https://user-images.githubusercontent.com/2953267/33464216-47f2ec30-d652-11e7-80ba-05cf9876cb38.png)

**Internet Explorer 11.64.16299.0 (update versions: 11.0.48)**
![image](https://user-images.githubusercontent.com/2953267/33464255-67d89950-d652-11e7-8a7d-4c677893ad5e.png)

**Comment by bhovhannes** [comment]
Thank you for the demo pen!
I completely agree on removing that option.
It will be major release just in case this is a breaking change for some
folks.
