### ISSUE TITLE
Module build failed: TypeError: Cannot read property 'limit' of null

### ISSUE THREAD

**Issue by MilosRasic** [bhovhannes/svg-url-loader#106]
svg-url-loader@2.1.0

When the loader is used without options, like this:
```
				{
					test: /\.svg$/,
					exclude: /font/,
					loader: "svg-url-loader"
				},
```

Build fails with "Module build failed: TypeError: Cannot read property 'limit' of null", once for every svg file the loader attempted to process.

This is easily worked around by supplying empty options:
When the loader is used without options, like this:
```
				{
					test: /\.svg$/,
					exclude: /font/,
					loader: "svg-url-loader"
				},
```
but it would be nice to not have to do this, like with other loaders.

My guess is old loader-utils would return an empty object when there's no options but the new ones return null.

**Comment by bhovhannes** [comment]
This is fixed in 2.1.1
