### ISSUE TITLE
query param no longer returns an empty object

### ISSUE THREAD

**Issue by jagretz** [bhovhannes/svg-url-loader#107]
I recently built with the latest version and it broke the our build due to some changes.

index.js line 10 previous returned an empty obj `{}` when this.query was undefined or null, 
`var query = loaderUtils.getOptions(this);`

it now returns undefined which causes line 12,
`var limit = query.limit ? parseInt(query.limit, 10) : 0;`

to throw a TypeError trying to access the `limit` property.

This actually looks to be an update to `parseQuery.js` from the loader-utils npm module that is packaged into this module. However, the most previous update to that moduel was in March of this year so it  wasn't until this version was updated that we noticed the breaking change.

I was able to fix this in my webpack configuration by adding a `query` param to the loader. Previously, that param was not necessary.

```
module: {
	loaders: [
		{
			loader: "svg-url-loader",
			test: /\.svg/,
			query: {}
		}
                // other loaders
```

**Comment by bhovhannes** [comment]
This is fixed in 2.1.1
