### ISSUE TITLE
when used with svg fonts, font is not loaded

### ISSUE THREAD

**Issue by macolo** [bhovhannes/svg-url-loader#111]
I am using svg-url-loader in my webpack config file:
```
            {
                test: /\.svg$/i,
                // fonts need to be loaded
                // exclude: /fonts/,
                loader: "svg-url-loader",
            },
```
This CSS is required in `main.js`, it specifies an svg font:
```
@font-face {
    font-family: 'Sofia Pro';
    src: url('./_webfonts/sofiapro-bold-webfont.eot');
    src: url('./_webfonts/sofiapro-bold-webfont.eot?#iefix') format('embedded-opentype'),
         url('./_webfonts/sofiapro-bold-webfont.woff2') format('woff2'),
         url('./_webfonts/sofiapro-bold-webfont.woff') format('woff'),
         url('./_webfonts/sofiapro-bold-webfont.ttf') format('truetype'),
         url('./_webfonts/sofiapro-bold-webfont.svg#sofia_probold') format('svg');
    font-weight: bold;
    font-style: normal;
}
```

In this case, all other font formats also dont work. If uncomment the `exclude` for svg-url-loader, the `woff` is loaded correctly.

**Comment by Neunerlei** [comment]
I stumbled upon this issue today.
It seems to have an issue with the Hashtag inside the font declarations. 
After looking through the source code, there are two solutions to this issue: 
Either, set the [Encoding](https://github.com/bhovhannes/svg-url-loader#encoding) to "base64".
Or set the [NoQuotes](https://github.com/bhovhannes/svg-url-loader#noquotes) parameter to TRUE.
Both fixes the issues
Cheers!

**Comment by bhovhannes** [comment]
This is no longer an issue, closing this.
