### ISSUE TITLE
Module not found: 'svg-url-loader'

### ISSUE THREAD

**Issue by nottoseethesun** [bhovhannes/svg-url-loader#112]
After running `yarn` as normal, now `require('svg-url-loader!../../images/foo.svg');` (and `require('!svg-url-loader!../../images/foo.svg');` ) results in the error message, `Module not found: 'svg-url-loader'` under `webpack@1.14.0`.   Before that run of `yarn`, the error was never seen, and the error is not seen under `webpack@3.3.0`.  The project has many packages, all of which load fine under `webpack@1.14.0`, except `svg-url-loader`.

**Comment by bhovhannes** [comment]
@nottoseethesun I don't see any point in supporting webpack 1. Upgrade to webpack 2/3 is easy and webpack 2/3 has performance improvements which everyone wants to see in his production bundle.
Maybe loader code contains something which makes webpack 1 unhappy.
Can you come back with a sample repo illustrating the issue?

**Comment by nottoseethesun** [comment]
Yes you are correct, the issue was webpack 1 - I've upgraded as you suggested and problem solved.
