### ISSUE TITLE
svg files don't seem to be recognized in scss files by svg-url-loader

### ISSUE THREAD

**Issue by dimafeldman** [bhovhannes/svg-url-loader#114]
Hi,
I'm trying to use svg-url-loader within a scss file, and it seems to always return the url of the file path instead of the encoded sctring.

my webpack rules are:
```
{
                test: /\.css$/,
                loader: 'style-loader!raw-loader'
            },
            {
                test: /\.scss$/,
                loader: 'style-loader!raw-loader!sass-loader'
            },
            {
                test: /\.svg$/,
                use: {
                    loader: 'svg-url-loader',
                    options: {
                        noquotes: false,
                        limit: 100000
                    }
                }
            }
```

and my .scss file:
```
.logo {
    background: url('../images/logo.svg') no-repeat center;
}

```

css output: 
```
.logo {
    background: url('../images/logo.svg') no-repeat center;
}

```

what am I missing? Thanks!

**Comment by bhovhannes** [comment]
Your setup is OK.
There is a test in this repo exactly with your setup. Maybe logo.svg is
larger than limit.

**Comment by dimafeldman** [comment]
might be, but I've set the limit to 100000, the logo is about 1.5kb :)
maybe i'm not setting the limit correctly?

**Comment by dimafeldman** [comment]
I found the issue, I was missing the css-loader in my config. when replacing raw-loader to css-loader it resolved the issue.
