### ISSUE TITLE
Supporting IDs in SVG for filtering?

### ISSUE THREAD

**Issue by vadimshvetsov** [bhovhannes/svg-url-loader#123]
Is it possible to use filters with loader?

For example, I have an SVG like below:
```
<svg version="1.1" xmlns="http://www.w3.org/2000/svg">
    <filter id="blur">
        <feGaussianBlur stdDeviation="25"/>
    </filter>
</svg>
```
For using this filter on my background I need to have styles like that:

```
article {
        filter: url(../img/blur.svg#blur); /* TODO Need omit for getting working, as data not working */
}
```
How to point to #blur after the output file generated?

**Comment by bhovhannes** [comment]
It is currently impossible with this loader. 
In order to make this working loader should parse SVG, understand IDs, and encode only the part referenced from `url()` part.
This is a non-trivial work and is a little outside of scope of this loader.

**Comment by vadimshvetsov** [comment]
@bhovhannes Thanks. Maybe there is way to omit certain file in CSS with some declarations before? In `.js` files I can manually configure file like below: 
`import logo from '!!svg-url-loader?noquotes!../../img/logo.svg'`

**Comment by bhovhannes** [comment]
You may want to assign a different extension to the files you want to go through svg-url-loader and tweak a regex in your webpack config to match only that files

**Comment by vadimshvetsov** [comment]
@bhovhannes Thanks a lot, as workaround it's okay for now.
