### ISSUE TITLE
Content is uri encoded

### ISSUE THREAD

**Issue by gizm0bill** [bhovhannes/svg-url-loader#149]
https://github.com/bhovhannes/svg-url-loader/blob/e1459fd6d2429ebb0276fe1e2ed9f7f8d984c801/index.js#L33

why? please remove

**Comment by bhovhannes** [comment]
Any issues with this?

**Comment by gizm0bill** [comment]
yes, I'm trying to `require('/path/to.svg')` and I get back a: `data:image/svg+xml,%3Csvg xmlns='...` which is obviously not good for things like `div.innerHTML = svgStr`... also `data:image/svg+xml,` is not needed

**Comment by bhovhannes** [comment]
Encoding of special characters like `<` is absolutely required if you use
ascii svg encoding in data-uri string.
You may want to read through original article from CSS-tricks about that.
In your case I recommend to use just raw-loader and assign returned string
to your innerHTML.

**Comment by gizm0bill** [comment]
ah yes, you're right. raw loader works good for my case
