### ISSUE TITLE
Integrate SVG-O to strip out unnecessary lines embedded in svgs

### ISSUE THREAD

**Issue by danielduan** [bhovhannes/svg-url-loader#198]
There's this tool that can optimize SVGs and get rid of unnecessary text within SVG files outputted by tools like Illustrator, Sketch, etc. It can sometimes reduce the file size by 50% or more.

https://github.com/svg/svgo

I think it makes sense to run our imports through this before the rest of the url loader conversion work.

Let me know if this is a good idea, I can help with a PR if needed.

**Comment by bhovhannes** [comment]
If I remember correctly, there is an svgo-loader. You can combine it with
svg-url-loader to achieve needed result.

**Comment by danielduan** [comment]
Thanks! wasn't aware of that loader. Perhaps this could be listed in the docs too?
