### ISSUE TITLE
Images svg aren't loading, how to fix?

### ISSUE THREAD

**Issue by UlpiusCode** [bhovhannes/svg-url-loader#282]
CSS Background Image not displaying
1. in browser:
http://funkyimg.com/i/2QLU7.png
2.  scss class:
http://funkyimg.com/i/2QLU8.png
3. webpack.dev.js:
http://funkyimg.com/i/2QLU9.png

**Comment by alexcheuk** [comment]
Also getting this problem

**Comment by alexcheuk** [comment]
I ended up fixing that issue by removing the `noquotes: true` from options

**Comment by bhovhannes** [comment]
Thanks guys, and sorry for extremely late reply. Didn't have much time for open-source stuff.

@UlpiusCode , @alexcheuk already gave a valid answer, so I am closing this one.
Feel free to comment.
