### ISSUE TITLE
Question: is there a way to disable plugin inline for few SVG?

### ISSUE THREAD

**Issue by dorianrod** [bhovhannes/svg-url-loader#302]
Hi,

Thanks for this plugin, works perfectly. 

I use a configuration to import all svg content into my CSS files thanks to my webpack configuration (webapck 3):
{
            test: /\.svg/,
            use: [{
                loader: 'svg-url-loader',
                options: {
                    stripdeclarations: true,
                    encoding: 'base64'
                }
            },
            {
                loader: 'image-webpack-loader',
                options: {
                }
            }]
        }

 For some svg I'd like to not import them but keep the link to the file instead. Is it possible?

Example:

.includedSVG {
	background-image: url('path_to_ressources/file.svg'); //content is loaded in my file
}

.notIncludedSVG {
	background-image: url('svg-url-loader?-disable,path_to_ressources/file.svg'); //DOEST NOT WORK, but I guess it's something like this
}

Have a good day
Dorian

**Comment by bhovhannes** [comment]
Hi @dorianrod ,

The solution which come to my mind is that you can use different webpack rules for svgs to be imported via svg-url-loader and as urls. Something like this:
```javascript
{
  // this will tell webpack to apply loader only for files ending with `.encoded.svg`
  test: /.encoded.svg/,
  use: [{
    loader: 'svg-url-loader',
    options: {
      stripdeclarations: true,
      encoding: 'base64'
    }
  }]
},
{
  // this will tell webpack to apply loader only for files ending with `.as-url.svg`
  test: /.as-url.svg/,
  use: [{
    // put any loader you want here, 
    // perhaps `url-loader` with boolean `limit` option will do the trick
  }]
}
```

Sorry for extremely late reply, I didn't have much time for open-source stuff.
I am closing this issue, but feel free to add your comments here.
