### ISSUE TITLE
Update README to include webpack options configuration for supported parameters

### ISSUE THREAD

**Issue by tylercreller** [bhovhannes/svg-url-loader#323]
Currently there is only documentation on how to apply supported parameters via require. Including the webpack versions of these would increase the verbosity of the documentation. I can submit a PR for this if it is something you desire!

**Comment by bhovhannes** [comment]
Hi,

https://github.com/bhovhannes/svg-url-loader#in-css-with-webpackconfigjs-below this section has a webpack config example.
However I agree that having more examples will be better than just link to webpack loaders docs.

In my opinion it will be best to have examples in the format which is ready for copy/paste, for most used scenarios.

If you can add some examples under https://github.com/bhovhannes/svg-url-loader#usage section that will be awesome.

**Comment by tylercreller** [comment]
Sounds good! I've opened up a pull request here https://github.com/bhovhannes/svg-url-loader/pull/324

 Let me know if we would prefer a different format.
