### ISSUE TITLE
The benefits of data:xyz style vs. SVG sprites

### ISSUE THREAD

**Issue by dko-slapdash** [bhovhannes/svg-url-loader#341]
Hi.

I just noticed that one thing is not mentioned anywhere in README, but it may have some value to the users.

So, **images with data url appear on the screen way faster than all regular images (even if the regular images are in the browser cache already)**, at least in Chrome. With data url, the images appear on the screen at the same time the text around them appears. With regular images, they're rendered 100-400ms after the text (even with width/height provided, and the image file is in the cache).

So this plugin improves the rendering impression to the user.

**Comment by bhovhannes** [comment]
yep, perhaps this can be worth mentioning in readme, thanks!
