### ISSUE TITLE
Please update `file-loader` to latest version

### ISSUE THREAD

**Issue by alexander-akait** [bhovhannes/svg-url-loader#363]
Latest version of `file-loader` is https://github.com/webpack-contrib/file-loader/blob/master/package.json#L3. We switch to ES modules syntax and it is allow to tree shake code, I would suggest to do it too:
- update `file-loader` to latest version, introduce `esModule` option (default value is `false`) and do minor release
- switch `esModule` to `true` and do major release

**Comment by bhovhannes** [comment]
Does esModules=true work for file-loader for webpack version 4?

**Comment by evilebottnawi** [comment]
@bhovhannes yes, but i recommend to use the `5` version

**Comment by bhovhannes** [comment]
Temporary solution was to bump file-loader version to v5, passing `esModule=false` to `file-loader`.

That was done in #346 .

I am not ready to enable `esModule=true` by default as not every consumer if this package has babel loader. And thus I am not going to introduce any new option to this loader at this moment. I plan to think about this when webpack 5 will be released.

@evilebottnawi, just out of curiosity, do you have any evidence showing that writing code with `export default ...` contributes better to bundle size?

**Comment by evilebottnawi** [comment]
@bhovhannes 
> I am not ready to enable esModule=true by default as not every consumer if this package has babel loader.

You don't need babel for `import`, webpack handle that on own side. We support `import` since webpack@4 without any additional loaders.

> just out of curiosity, do you have any evidence showing that writing code with export default ... contributes better to bundle size?

Yes, it is reduce bundle size - https://webpack.js.org/plugins/module-concatenation-plugin/. It is allow remove unnecessary module and include value of module directly. Less modules - less size- fast runtime

**Comment by bhovhannes** [comment]
Thanks for info.
Then why `esModule` option is not true by default in `file-loader`?

**Comment by evilebottnawi** [comment]
https://github.com/webpack-contrib/file-loader#esmodule - default is `true`

**Comment by bhovhannes** [comment]
I mean it was introduced to be false by default and then was made to be true. What was the reason for that?

**Comment by evilebottnawi** [comment]
Module concatenation, simple example

**string.js**

```js
export default "text";
```

**index.js**

```js
import text from './string.js';

console.log(text);
```

When you run webpack in production mode and got only one module:
```js
var text_module_concatenation_variable = 'text';

console.log(text);
```

No extra module. It is very very very simple case.

**Comment by bhovhannes** [comment]
Thanks for example. I am trying to understand why you suggest to release 2 versions and introduce a new option - `esModule` (like it was done in `file-loader`), if it works ok starting from webpack 4.

Well yes, if I care about folks using webpack 3 I should probably do like that and have that option in place.
However if I support only webpack 4 and above, why not to **always** pass `esModule=true` to `file-loader`?

**Comment by evilebottnawi** [comment]
> However if I support only webpack 4 and above, why not to always pass esModule=true to file-loader

Some other loaders can't support ES module import so it should be setup from configuration

**Comment by bhovhannes** [comment]
Which loaders? Can't we try to upgrade them as well?

**Comment by evilebottnawi** [comment]
@bhovhannes Any, any developer can create an own loader, so we can't update them, just introduce new option and do it true by default in next major release

**Comment by bhovhannes** [comment]
I understand, just wondering if there are popular loaders which still does
not support esModule stuff.

**Comment by evilebottnawi** [comment]
All popular loaders inside webpack-contrib and they support esModule :+1:
