### ISSUE TITLE
Incorrect Data URI content when using issuer test

### ISSUE THREAD

**Issue by allista** [bhovhannes/svg-url-loader#365]
Hi, I'm trying to use svg-url-loader along with svgr, which requires to test for issuer to only use svgr in jsx context. I also need to be able to import svgs as data uris from jsx. While trying to do so I've encountered the following data uri generated by svg-url-loader:

`data:image/svg+xml,module.exports = 'data:image/svg+xml,%253Csvg width='18' height='19' viewBox='0 0 18 19' fill='none' xmlns='http://www.w3.org/2000/svg'%253E %253Cpath d='M9.04158...` (the path is omitted)

which, of course, cannot be displayed.

Here's the (simplified) code that imports the svg:

```jsx
import React from 'react';
import starUrl from './star.svg';

export default function ComponentWithIcon() {
  return (
    <div>
      <img src={starUrl} alt="icon" />
    </div>
  );
}
```

and the rules section of the webpack config that produces this follows:

```js
      {
        test: /\.svg$/,
        issuer: {
          test: /\.(tsx?|jsx?)$/,
        },
        use: {
          loader: 'svg-url-loader'
        },
      },
      {
        test: /\.svg$/,
        use: {
          loader: 'svg-url-loader'
        },
      },
```
(_no other loaders for svg are configured_)
If I remove the first rule with issuer test, the same import produces correct data, without the `module.exports = 'data:image/svg+xml,`

**Comment by bhovhannes** [comment]
Hi, I don't follow, why you have 2 rules using svg-url-loader in your
webpack config?
In the code you have described svgr is not used at all...

**Comment by bhovhannes** [comment]
Closing this because I've received no feedback. Comment here if is it still the issue for you, I am ready to investigate.
