### ISSUE TITLE
Doesn't working on image tag

### ISSUE THREAD

**Issue by raphaelbs** [bhovhannes/svg-url-loader#388]
Hi!
First of all, this loader is amazing! Kudos!

The project that I'm working on has a lot of svgs as img sources, e.g.:

```jsx
import CoolSvg from '../assets/Cool.svg';

<img src={CoolSvg} />
```

The output of this loader is producing an additional quotes that is preventing the SVG to appear on the page:

![image](https://user-images.githubusercontent.com/11169832/81837585-6b97fd80-951b-11ea-9b0f-e046f794e759.png)

If I manually remove it, it does work.

**Comment by raphaelbs** [comment]
Ops, I was using the version 2.x.x.
After upgrading it to version 5, worked!

**Comment by bhovhannes** [comment]
Glad for you!
There used to be `noQuotes` option, but with recent version of html-loader and svg-url-loader this option is no longer needed as loaders themselves figure out whenever they should append quotes or not.
