### ISSUE TITLE
Missing webpack in peerDependencies for yarn@2 compatibility

### ISSUE THREAD

**Issue by irudoy** [bhovhannes/svg-url-loader#390]
```
yarn set version berry
yarn add svg-url-loader

➤ YN0002: │ svg-url-loader@npm:5.0.0 doesn't provide webpack@^4.0.0 || ^5.0.0 requested by file-loader@npm:6.0.0
```

The problem: https://yarnpkg.com/advanced/error-codes#yn0002---missing_peer_dependency
Detailed explanation: https://dev.to/arcanis/implicit-transitive-peer-dependencies-ed0

**Comment by bhovhannes** [comment]
@irudoy thank you for reporting this.  
The fix has been released in version `5.0.1` and it is also present in `6.0.0`.
