### ISSUE TITLE
Please Add CHANGELOG.md

### ISSUE THREAD

**Issue by Yegorich555** [bhovhannes/svg-url-loader#391]
Thank you for your package, but I'm surprised not to see CHANGELOG.md.
This is must-have for good package and helps to understand is it possible update package without breaking changes or not.

Could you add CHANGELOG.md?

**Comment by bhovhannes** [comment]
[Releases](https://github.com/bhovhannes/svg-url-loader/releases) already have that information.

I don't want to duplicate the same info in `CHANGELOG.md`.
