### ISSUE TITLE
svg not appears

### ISSUE THREAD

**Issue by liorsharabi** [bhovhannes/svg-url-loader#46]
hi 

i'm trying to use the svg loader:
```
let img2 = require('svg-url?noquotes!../../../resources/light/images/icons/svg/column_chart_colored.svg');
        return (
                <img src={img2 }/>
);
```

there's no error but the svg is not appear (it's like it didn't find it in he's path)
what do you think could be the problem?

in the webpack config:
 ```
    test: /\.svg/,
        loader: 'svg-url-loader'
```

**Comment by bhovhannes** [comment]
Try to write like this (notice `!!` in require call):
```
let img2 = require('!!svg-url?noquotes!../../../resources/light/images/icons/svg/column_chart_colored.svg');
return (
    <img src={img2 }/>
);
```

It seems that your require call and webpack config result in svg-url-loader applied twice to the same icon, resulting in invalid output.

**Comment by liorsharabi** [comment]
it works!
thank you so much

**Comment by Hum4n01d** [comment]
@bhovhannes How would I achieve this with ES6?

**Comment by Hum4n01d** [comment]
Currently I’m doing this: `import mustachio from '!!svg-url-loader?noquotes!../images/mustachio.svg'`

That’s pretty ugly though. Isn’t there a better way?
