### ISSUE TITLE
when generate Data URLs,svg (image.src) content is not correct 

### ISSUE THREAD

**Issue by 1000copy** [bhovhannes/svg-url-loader#48]
bug reproduce procedure 

1. main html:main.html

```
    <html>
      <body>
        <div>Hello svg</div>
        <script type="text/javascript" src="bundle.js"></script>
      </body>
    </html>
    
```

2. one svg file named 100.svg,just filled circle:
    
`    <svg xmlns="http://www.w3.org/2000/svg"><circle cx="10" cy="10" r="10" fill="#000"/></svg>
    `
3. import svg file from main.js:

```
    var img1 = document.createElement("img");
    img1.src = require("./100.svg")
    document.body.appendChild(img1);
```
    
3. and config svg-url-loader in config file (webpack.config.js)：
 
```
    module.exports = {
      entry: './main.js',
      output: {
        filename: 'bundle.js'
      },
      module: {
        loaders:[
          {test: /\.svg/, loader: 'svg-url-loader?limit=10000'},
        ]
      }
    };
```

limit is larger enough force loader make Data URLs other than external svg file,and install loader:

`    npm i svg-url-loader --save-dev`
    
then run bundle and open main.html:

`    webpack`
    
img is break link .but if limit=1 ,then OK.

and one more thing ,I find :
      
`      module.exports = "\"data:image/svg+xml;charset=utf8,`

in last lines of bundle.js .I think` \"` is root cause .

thank you for attention .

**Comment by bhovhannes** [comment]
When `limit=1` loader delegates to file-loader, so your svg will be treated as any other image.

**Comment by 1000copy** [comment]
👍  it works
