### ISSUE TITLE
Remove `charset=utf8`

### ISSUE THREAD

**Issue by GreLI** [bhovhannes/svg-url-loader#60]
`;charset=utf8` part in css `url()` seems to be excessive. It looks like modern browsers can parse such SVGs correctly without it, while IE needs url-encoding of non-ascii symbols anyway.

**Comment by bhovhannes** [comment]
@GreLI, do you know any official source about browser support you've mentioned?
I want to understand which browsers we'll break if remove `;charset=utf8` part...

**Comment by GreLI** [comment]
With ascii-only symbols it's 100% works everywhere. I've used it with a large russian portal (Yandex). With non-ascii my [quick test](http://codepen.io/GreLI/pen/VPRzNJ) shows that works also everywhere, but only uri-encoded in IE. It seems to have no difference in the respect to presence of charset string.

I believe, it's a combo of a CSS parser and browser URL parser. IE parser is a bit specific one.

**Comment by GreLI** [comment]
Actually, after some playing with it, it seems that *any* value of `charset` make no effect. Either browsers are too smart and detect it automatically, or it just useless.

**Comment by GreLI** [comment]
No, it doesn't seem to detect (url-encoded) charset other than utf-8, even if I specify it. Probably, URL strings are being parsed as utf-8 by default.

**Comment by bhovhannes** [comment]
Released in v2.0.2

**Comment by GreLI** [comment]
Cool! Thanks!
