### ISSUE TITLE
Add a way to pass fill color as a variable

### ISSUE THREAD

**Issue by gajus** [bhovhannes/svg-url-loader#86]
It would be nice if I could do (a variation) of this:

```css
background-image: url('../../styles/icons/angle-right.svg?fillColor=#f00f00');
```

The resulting SVG would be generated using the provided parameters.

**Comment by bhovhannes** [comment]
@gajus the loader currently does not do any transformations on SVG source. It just encodes the contents of SVG file.
It will be better to implement transformations like this as a separate loader and pass output of that loader to input of svg-url-loader to make them work in a tandem. Additionally transformer loader can minimize SVG using svgo.

**Comment by gajus** [comment]
For the record, I've ended up using https://github.com/Pavliko/postcss-svg.

I agree that this module should stay lean.

Good to close?

**Comment by bhovhannes** [comment]
Thanks for sharing postcss-svg and ideas for future improvements!
