### ISSUE TITLE
Possibility to phrase through html

### ISSUE THREAD

**Issue by hendrikeng** [bhovhannes/svg-url-loader#95]
Hey there, is it possible with the loader to phrase through the html and replace e.g. <img src="file.svg"> with the corresponding data:uri ? i am a bit confused by all the loaders, thanks a lot

**Comment by bhovhannes** [comment]
@hendrikeng this is outside of scope of this loader.
To achieve desired effect you may want to use this loader in a tandem with [html-loader](https://github.com/webpack-contrib/html-loader). Reading through "Usage" section it appears that `html-loader` can call other loaders for `<image>` tags.

**Comment by hendrikeng** [comment]
@bhovhannes thanks a lot :-)
